### PR TITLE
Fix version_set compilation bug

### PR DESCRIPTION
**Pull request by fgallaire**

### CODE REVIEW

**Comment by matthewvon** [comment]
Yes, pull request accepted.  Will merge soon.

What platform / compiler gave warning / error?  I would like to reproduce.

**Comment by fgallaire** [comment]
https://github.com/basho/leveldb/issues/87

**Comment by matthewvon** [comment]
In a perfect world I would be able to find OSX 10.7.x machine with related XCode to verify before / after effects of the change.  In my world that did not happen.  I have verified that the change does NOT break my 10.8 OSX XCode and Linux builds.  Also found C or C++ spec validating the usage ... merging.

**Comment by matthewvon** [comment]
p.s.  I manually made the same change in branch mv-hot-threads1 ... expect a merge conflict there until that branch goes to master also.

**Pull request merged**
