### PR TITLE
Write value of executing options to log upon database open.

### PR DESCRIPTION
**Pull request by matthewvon**
Diz requested that all options at the time of database open be placed in LOG to allow technical review.  This only logs global options, not the read and write specific options.

### CODE REVIEW

**Comment by rzezeski** [comment]
This worked fine for me but I created a branch to write names where possible instead of just emitting pointers which seems mostly useless.

+1 to merge

https://github.com/basho/leveldb/compare/rz-mv-option-logging-use-names

**Comment by rzezeski** [comment]
Also, as a note, the cacheleak test fails for me intermittently on this branch and master.

**Comment by matthewvon** [comment]
Read and Write options are not available to leveldb at time of database open.  They are available only at time of an actual read or write.  Was not in the mood to create necessary code to ensure options only written the first time encountered ... i.e. I got enough performance concerns this round without creating another.  Maybe next release.  The underlying problem though is solved.  Critical options that were previously NOT passing from app.config to leveldb are now verified to pass.

**Comment by rzezeski** [comment]
I'm not sure I follow.  I was referring to the `comparator` and `filter_policy` options.  Both of them have a human readable string representation available yet you log the pointers.

**Pull request merged**
