### PR TITLE
- adapted constant initialisers type to mach type of initialized variabl...

### PR DESCRIPTION
**Pull request by franzhaas**
...e
- this fixes overflow on 32bit machines

### CODE REVIEW

**Comment by seancribbs** [comment]
We don't support 32-bit architectures.

**Comment by matthewvon** [comment]
This is a painless request.  Will work it into another PR.  Reopening it to remind me to do the work.

**Comment by matthewvon** [comment]
I am going to put this code into mv-timed-grooming branch.  It will work its way to develop, then master, on that work path.  Why?  Because this way the change will be seen on more machines before finally committed. 

I will close this PR only once mv-timed-grooming goes to develop.

**Comment by matthewvon** [comment]
mv-timed-grooming merged to develop a couple of days ago.  Please proof and close this PR if acceptable.

**Pull request closed without merging**
