### PR TITLE
Make compatible with Go bindings

### PR DESCRIPTION
**Pull request by icholy**
These changes are needed to work with the leveldb [Go bindings](https://github.com/jmhodges/levigo)

### CODE REVIEW

**Comment by matthewvon** [comment]
Looked at the code, all looks fine.  It will be a few weeks before this moves to develop. 

I once shoved community code that also looked really simple to develop that had side effects with other code.  Not risking that again even though this is so simple. I will build and test first.

 I will keep you posted, but assume this approved just not happening in a timely fashion.

**Comment by icholy** [comment]
@matthewvon ping, just making sure this hasn't been forgotten about.

**Comment by matthewvon** [comment]
I forgot.  Too many things moving at Basho all at once.  No way this week or next.  Week of 19th has some promise.

**Comment by icholy** [comment]
ok, thanks.

**Comment by icholy** [comment]
@matthewvon ping.

**Comment by matthewvon** [comment]
nope.  still working to get new product out the door by end of month.

**Comment by icholy** [comment]
ping?

**Comment by icholy** [comment]
ping

**Comment by icholy** [comment]
@matthewvon c'mon

**Comment by matthewvon** [comment]
we are 2 months behind on a major deliverable.  this does not go into code base without a full test cycle even though it looks fine on paper.  that test cycle happens after new product ships.

**Comment by matthewvon** [comment]
IF nothing goes ballistic tomorrow morning, I am going to copy your changes into PR 171 and start the 6 day test cycle.  If that passes all tests, your code will merge with PR 171 and I will comment here before deleting this PR.

**Comment by matthewvon** [comment]
What do you pass to leveldb_free, i.e. what type object?

**Comment by matthewvon** [comment]
Merged these changes with PR 171.  Awaiting notes about leveldb_free() before finalizing commit to develop branch.

**Comment by icholy** [comment]
@matthewvon you're supposed to use it when freeing anything that leveldb allocates for you. See https://github.com/jmhodges/levigo/blob/master/db.go

**Comment by matthewvon** [comment]
leveldb_free() is only appropriate for char \* values such as the return from leveldb_get().  If used on the return value from leveldb_open(), you would be in a world of hurt.  leveldb_open's return value is removed via leveldb_close().  I strongly suggest you change the parameter type from void \* to char \* so the compiler can help identify misuse.

**Comment by icholy** [comment]
I'd rather just keep it the same as the official repo. https://github.com/google/leveldb/blob/e2446d08481f6e2be3579a89ea3c772995846f17/db/c.cc#L583-L593

**Comment by matthewvon** [comment]
I would appreciate if you tried compiling your code with the void \* parameter changed to char *.  Want to know if that actually causes a linkage failure.  Having reviewed both the db.go and the repository point you made, I think they did something unsafe ... and once in Basho code base I become responsible.  At minimum I will have to add warning comments.

**Comment by icholy** [comment]
```
./db.go:84: cannot use unsafe.Pointer(errStr) (type unsafe.Pointer) as type *C.char in argument to _Cfunc_leveldb_free
./db.go:100: cannot use unsafe.Pointer(errStr) (type unsafe.Pointer) as type *C.char in argument to _Cfunc_leveldb_free
./db.go:117: cannot use unsafe.Pointer(errStr) (type unsafe.Pointer) as type *C.char in argument to _Cfunc_leveldb_free
./db.go:151: cannot use unsafe.Pointer(errStr) (type unsafe.Pointer) as type *C.char in argument to _Cfunc_leveldb_free
./db.go:178: cannot use unsafe.Pointer(errStr) (type unsafe.Pointer) as type *C.char in argument to _Cfunc_leveldb_free
./db.go:186: cannot use unsafe.Pointer(value) (type unsafe.Pointer) as type *C.char in argument to _Cfunc_leveldb_free
./db.go:207: cannot use unsafe.Pointer(errStr) (type unsafe.Pointer) as type *C.char in argument to _Cfunc_leveldb_free
./db.go:220: cannot use unsafe.Pointer(errStr) (type unsafe.Pointer) as type *C.char in argument to _Cfunc_leveldb_free
./iterator.go:139: cannot use unsafe.Pointer(errStr) (type unsafe.Pointer) as type *C.char in argument to _Cfunc_leveldb_free
```

**Comment by matthewvon** [comment]
Wow, that sucks.  Thank you for the test.  Talked to coworker, we agree it will have to go in as is.  I will add comments hoping to help the innocent ... and add test for NULL pointer as input.  Other than that, the  code is already on the test servers.  Just waiting a few days for results.

**Comment by matthewvon** [comment]
delivered via PR 171

**Pull request closed without merging**
