### PR TITLE
Startup segfault/race condition [JIRA: RIAK-2349]

### PR DESCRIPTION
**Pull request by matthewvon**
Move the AddDB() call to point after all object initialization complete to eliminate race condition that leads to segfault.

Detail description here:

https://github.com/basho/leveldb/wiki/mv-startup-segfault

### CODE REVIEW

**Comment by bashopatricia** [comment]
create jira issue

**Comment by Basho-JIRA** [comment]
Per Matthew - Eleveldb tag 2.0.11 addresses PR 184.  It can be used in all Riak releases.  

**_[posted via JIRA by Patricia Brewer]**_

**Comment by matthewvon** [comment]
The customer reporting the segfault has confirmed the fix.

**Comment by Basho-JIRA** [comment]
Once we update the dependencies this should be closed as well. 

**_[posted via JIRA by Douglas Rohrer]**_

**Pull request merged**
